language: node_js
node_js:
  - "8"

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod

deploy:
  provider: azure_web_apps
  skip_cleanup: true
  verbose: true
  on:
    branch: master
