language: node_js
node_js:	
  - "8"

services:
  - docker

install: true

script:
  - docker build --build-arg CODECOV_TOKEN=$COVERAGE_TOKEN -t esipe-credentials-client .

deploy:
  provider: script
  script: bash scripts/deploy.sh
