services:
  - docker

script:
  - docker build --build-arg CODECOV_TOKEN=$COVERAGE_TOKEN -t $DOCKER_USERNAME/esipe-credentials-client .

deploy:
  provider: script
  script: bash scripts/docker_push.sh
